pipeline {
  agent any
  environment {
    APP_NAME = "auto_sql"
    DOCKER_IMAGE_NAME = "auto_python"
    TARGET = "${params.TARGET}" 
    MODULE = "${params.MODULE}"
    tenantSid = "${params.tenantSid}"
    tenantId = "${params.tenantId}"
    WORKSPACE = "/var/lib/jenkins/workspace/auto_deploy_app_db"
  }
  stages {
    stage('构建前准备') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'builduser', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
        script {
          sh """                        
               if docker inspect ${APP_NAME} >/dev/null 2>&1; then
                   docker stop ${APP_NAME}
                   docker rm ${APP_NAME}
               fi
      

             """
              }
            }
      }
    }
    
    stage('构建docker镜像') {
      steps {
        script {
          def dockerfile = 'jenkins/Dockerfile'
          def image = docker.build("${DOCKER_IMAGE_NAME}", "--build-arg TARGET=${TARGET} --build-arg MODULE=${MODULE} --build-arg tenantSid=${tenantSid} --build-arg tenantId=${tenantId} -f ${dockerfile} .")
          sh """
                docker run -itd --name ${APP_NAME} -e MODULE=${MODULE} -e TARGET=${TARGET} -e tenantSid=${tenantSid} -e tenantId=${tenantId} ${DOCKER_IMAGE_NAME}
             """

         
        }
      }
    }

   }
}

  
